### PR TITLE
(#21) Add method to return canonical path forms

### LINKED ISSUE #21: Canonical / unique path forms
We should introduce a method that is allowed to perform disk IO and converts a path to its "canonical" / "unique" form.

On case-insensitive file systems, it should convert the path to the correct / disk case.

Also, it should resolve symlinks and provide an option to resolve or ignore the symlinks on the go.

I am looking to design it similarly to [`File::getCanonicalPath`](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#getCanonicalPath--) or maybe [`Path.toRealPath`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html#toRealPath-java.nio.file.LinkOption...-) in OpenJDK.

### PR DESCRIPTION
**Pull request by Kataane**
#### Description
This pull request introduces a new `DiskUtils` class designed to generate canonical path forms for both Windows and POSIX platforms. It ensures consistent path formatting across different operating systems, improving the reliability and portability of file path handling in our project.

#### Changes
- **DiskUtils Class**
  - Implemented the `DiskUtils` class with methods to create canonical path forms.
  - Supported platforms: Windows and POSIX.

- **Tests**
  - Added comprehensive tests for the `DiskUtils` class.
  - Verified functionality on both Windows and POSIX platforms to ensure compatibility and correctness.

#### Testing
- All new tests for `DiskUtils` have been executed and passed on both Windows and POSIX environments.

 [Canonical / unique path forms #21 ](https://github.com/ForNeVeR/TruePath/issues/21)

- Closes #21

### CODE REVIEW

**Comment by ForNeVeR** [comment]
Unix tests have been broken with quite bizarre results:
```
Expected: "/home/runner/work/TruePath/TruePath/TrueP"···
Actual:   "/HOmE/runNer/WORk/TruEPaTh/TRUEPaTh/TRuEP"···
```

**Comment by Kataane** [comment]
@ForNeVeR fix

**Review by ForNeVeR — APPROVED** [review]
Thanks! I have updated the API a bit to integrate with `AbsolutePath`.

**Comment by ForNeVeR** [comment]
Guess what: random started to _randomly_ fire in tests :)

I am removing it.

**Pull request merged**
